config/routes.rb
ClothingApp::Application.routes.draw do
  get "admin/index" => "admin#index",:as => :main_view
  get "dashboards/new" => "dashboards#new",:as => :dashboard_view
  match "admin/disabled"=>"admin#disabled",:as=>:disabled
  match "admin/edit_account/:id"=>"admin#edit_account",:as => :edit_user_account
  match "admin/update_account" => "admin#update_account",:as => :update_account
  get "home/index"=>'home#index',:as=> :home_index
  match '/profile' => "profile#view",:as => :profile
  devise_for :users, :controllers => {:registrations => "users/registrations",
                                      :confirmations => 'users/confirmations'}
  root :to => 'home#index'
  resources :sizes
  resources :category_products
  resources :product_saved
  resources :designer_liked
 get "admin/users"=>"admin#user_details"
 match "admin/user_pro"=>"admin#user_pro"
 match "admin/select_manag"=>"admin#select_manag"
  post  "categories/create_cate"=>"categories#create_cate"
  get "categories/new"=>'categories#new'
  get "/categories"=>'categories#index'
  get "/categories/show"=>'categories#show'
  get "/categories/edit"=>'categories#edit'
  match "/categories/delete"=>'categories#destroy'
  match "/categories/update"=>'categories#update'
 
  match "/designers"=>"designers#index"
  match "/designers/create"=>"designers#create"
  match "/designers/new"=>"designers#new"
  get "/designers/show"=>"designers#show"
  get "/designers/edit"=>"designers#edit"
  match "/designers/update"=>"designers#update"
  get "/designers/delete"=>"designers#destroy"

  match "/products"=>"products#index",:as=>:product_index
  post "/product/create"=>"products#create",:as=>:product_create
  match "/product/new"=>"products#new",:as=>:product_new
  get "/product/show"=>"products#show",:as=>:product_show
  get "/product/edit"=>"products#edit",:as=>:product_edit
  match "/product/update"=>"products#update",:as=>:product_update
  get "/product/delete"=>"products#destroy",:as=>:product_delete


  get "/frontend/home"=>"frontend#home"
  get "/frontend/category_main"=>"frontend#category_main"
  get "/frontend/category_individual"=>"frontend#category_individual"
  get "/frontend/designer_main"=>"frontend#designer_main"
  get "/frontend/designer_individual"=>"frontend#designer_individual"
  get "/frontend/product_main"=>"frontend#product_main"
  match "/frontend/product_individual"=>"frontend#product_individual"
 match "/frontend/featured_subcate/:id"=>"frontend#featured_subcate" ,:as=>:frontend_featured_subcate
match "/frontend/designer_liked/:id"=>"frontend#designer_liked" ,:as=>:frontend_designer_liked
  match "/frontend/delete"=>"frontend#destroy",:as=>:frontend_delete
match "/get_prices"=>"frontend#price"
match "/data_saved"=>"frontend#res_back"

end

app/models/category.rb
class Category < ActiveRecord::Base
   	attr_accessible :name,:description,:parent_id,:is_featured,:image,
    :image_file_name,:image_content_type,
   	:image_file_size,:image_updated_at
  	has_many :sub_categories, :class_name => "Category",
    :foreign_key => "parent_id"
    has_many :category_products 
  has_many :products, :through => :category_products 
 	has_attached_file :image,
                    :column => 'image',
                    :styles => { :small => "45x50",:medium => "90x100",:large => "180x200",:xlarge => "270x300",:xxlarge => "360x400"},
                    :default_url => "/images/category/:style.png",
                    :url=>"/assets/category/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/category/:id/:style/:basename.:extension"
                    validates_attachment_content_type :image, :content_type => /\Aimage/

# validates :name,:presence=>true
end

app/models/category_product.rb
class CategoryProduct < ActiveRecord::Base
  attr_accessible :category_id, :product_id
  belongs_to :category
   belongs_to :product
end

app/models/countries.rb
class Countries < ActiveRecord::Base
  attr_accessible :name
end

app/models/designer.rb
class Designer < ActiveRecord::Base
  attr_accessible :name, :description,:city,:state,:country,:image,
  :image_file_name,:image_content_type,
   	:image_file_size,:image_updated_at
  has_many :designer_likeds
  has_many :users, :through=> :designer_likeds
  has_many :products
  	has_attached_file :image,
                    :column => 'image',
                    :styles => { :small => "45x50",:medium => "90x100",:large => "180x200",:xlarge => "270x300",:xxlarge => "360x400"},
                    :default_url => "/images/designer/:style.png",
                    :url=>"/assets/designer/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/designer/:id/:style/:basename.:extension"
                    validates_attachment_content_type :image, :content_type => /\Aimage/
end

app/models/designer_liked.rb
class DesignerLiked < ActiveRecord::Base
  attr_accessible :designer_id, :user_id
  belongs_to :designer
  belongs_to :user
end

app/models/product.rb
class Product < ActiveRecord::Base
 attr_accessible :name, :description,:sku,:image,:price,:is_featured, :designer_id,
 :image_file_name,:image_content_type,
   	:image_file_size,:image_updated_at
    has_many :category_products
 has_many :categories, :through => :category_products 
 belongs_to :designer
 has_many :product_saveds
 has_many :sizes
 has_attached_file :image,
                    :column => 'image',
                    :styles => { :small => "45x50",:medium => "90x100",:large => "180x200",:xlarge => "270x300",:xxlarge => "360x400"},
                    :default_url => "/images/product/:style.png",
                    :url=>"/assets/product/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/product/:id/:style/:basename.:extension"
                    validates_attachment_content_type :image, :content_type => /\Aimage/
before_create :generate_desig
 def generate_desig
 	if self.sku.nil? and self.new_record? 
 		self.sku=random_string(16)
 	end
 end
def random_string(length)
	chars = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ123456789'
	random = ''
	length.times { random << chars[rand(chars.size)] }
 return random

end

end

app/models/product_saved.rb
class ProductSaved < ActiveRecord::Base
  attr_accessible :product_id, :user_id, :size_id, :qty_selected
  belongs_to :product
  belongs_to :user
  belongs_to :size
  # validates :qty_selected, :presence=>true
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  attr_accessible :title, :name
end

app/models/size.rb
class Size < ActiveRecord::Base
   attr_accessible :product_id, :quantity, :price, :sizes
   belongs_to :product
    has_many :product_saveds
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:name,:city,:state,:country,:is_disabled,:role
  has_many :designer_likeds
  has_many :designers, :through=> :designer_likeds
  has_many :products
  has_many :product_saveds
  
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/helpers/frontend_helper.rb
module FrontendHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/views/admin/edit_account.html.erb
<%= form_for(:user,url: update_account_path(:id => "#{@user.id}"), html: { method: :post }) do |f| %>
<div><%= f.label :Name%><br />
  <%= f.text_field :name,:value => "#{@user.name}"%></div>

  <!--<div><%#= f.label :email %><br />
  <%#= f.email_field :email %></div>-->

  <div><%= f.submit "Update" %></div>
<% end %>

<%=link_to "Back",main_view_path%>

app/views/admin/index.html.erb
<table>
<tr>
	<td>
		<%=link_to "Category Management",categories_path%>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp

	</td>
	<td>
		<%=link_to "Product Management",product_index_path%>

	</td>
</tr>
<tr>
	<td>
		<%=link_to " Designer Management",designers_path%>&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp

	</td>
	<td>
		<%=link_to " User Management",admin_users_path%>

	</td>
</tr>
 <tr>
	<td>
		<%=link_to " Selected Management",admin_select_manag_path%>

	</td>
</tr> 
</table>
<div id="sign_out"><%=link_to "sign_out",destroy_user_session_path,:method => :delete%>
	</div>

app/views/admin/select_manag.html.erb
<table><% @usr.each do |e|%>
	<tr><td><%= e.name%></td>
		<td><% e.product_saveds.each do |s|%>
		<%= image_tag(s.product.image.url(:small))%>	<%end%></td>

		<td><% e.designer_likeds.each do |s|%>
		<%=image_tag(s.designer.image.url(:small))%>	<%end%></td>

	</tr>

	<%end%>

</table>

app/views/admin/user_details.html.erb
<table>
	<tr>
		<th>ID</th>
		<th>Name</th>
		<th>Email</th>
		<th>City</th>
		<th>State</th>
		<th>Country</th>
	</tr>
<%@users.each do |u|%>
	<tr>
		<td><%=u.id%></td>
		<td><%=link_to u.name,admin_user_pro_path(:uid=>u.id)%></td>
		<td><%=u.email%></td>
		<td><%=u.city%></td>
		<td><%=u.state%></td>
		<td><%=u.country%></td>
		<td><%= link_to "Edit",edit_user_account_path(:id => u.id)%></td>
		<td><%= link_to "Disabled",disabled_path(:id => u.id)%></td>
	</tr>
	<%end%>
</table>
<%=link_to "sign_out",destroy_user_session_path,:method => :delete%>

app/views/admin/user_pro.html.erb
<h1>Product Saved</h1>
<table><% @prod_saved.each do |p|%>
	<tr><td>
		<%=image_tag(p.product.image.url(:small))%> 
		</td>
	</tr><%end%>
	</table>
<h1>Designer Liked</h1>
<table><%@designer_like.each do |d|%>
	<tr><td>
		<%=image_tag(d.designer.image.url(:small))%> 
		</td>
	</tr><%end%>
	</table>

app/views/layouts/_categories.html.erb
	<table>
		<tr><td>C</td></tr>
		<tr><td>a</td></tr>
		<tr><td>t</td></tr>
		<tr><td>e</td></tr>
		<tr><td>g</td></tr>
		<tr><td>o</td></tr>
		<tr><td>r</td></tr>
		<tr><td>y</td></tr>
		<tr><td><br></td></tr>
		<tr><td><br></td></tr>
		<tr><td>D</td></tr>
		<tr><td>e</td></tr>
		<tr><td>t</td></tr>
		<tr><td>a</td></tr>
		<tr><td>i</td></tr>
		<tr><td>l</td></tr>
		<tr><td>s</td></tr>
	</table>
	

app/views/layouts/_designer.html.erb
<table>
		<tr><td>D</td></tr>
		<tr><td>e</td></tr>
		<tr><td>s</td></tr>
		<tr><td>i</td></tr>
		<tr><td>g</td></tr>
		<tr><td>n</td></tr>
		<tr><td>e</td></tr>
		<tr><td>r</td></tr>
		<tr><td><br></td></tr>
		<tr><td><br></td></tr>
		<tr><td>D</td></tr>
		<tr><td>e</td></tr>
		<tr><td>t</td></tr>
		<tr><td>a</td></tr>
		<tr><td>i</td></tr>
		<tr><td>l</td></tr>
		<tr><td>s</td></tr>
</table>
	

app/views/layouts/_header.html.erb
 <div id="header">
		<ul>
<li><%= link_to "Home" ,frontend_home_path%></li>
<li><%= link_to "Categories" ,frontend_category_main_path%></li>
<li><%= link_to "Products",frontend_product_main_path%></li>
<li><%= link_to "Designers" ,frontend_designer_main_path%></li>
<% if !user_signed_in? %>
<li><%= link_to "Login" ,new_user_session_path%></li>
<li><%= link_to "Sign_up" ,new_user_registration_path%></li>
<% end %>
</ul>

	</div>

app/views/layouts/_product.html.erb
<table>
		<tr><td>D</td></tr>
		<tr><td>e</td></tr>
		<tr><td>s</td></tr>
		<tr><td>i</td></tr>
		<tr><td>g</td></tr>
		<tr><td>n</td></tr>
		<tr><td>e</td></tr>
		<tr><td>r</td></tr>
		<tr><td><br></td></tr>
		<tr><td><br></td></tr>
		<tr><td>D</td></tr>
		<tr><td>e</td></tr>
		<tr><td>t</td></tr>
		<tr><td>a</td></tr>
		<tr><td>i</td></tr>
		<tr><td>l</td></tr>
		<tr><td>s</td></tr>
</table>
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ClothingApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:notice] %>
    <p class="flash-notice"><%= flash[:notice] %></p>
  <% end %>
 

<%= yield %>

</body>
</html>