config/routes.rb
ClothingApp::Application.routes.draw do
  get "admin/index" => "admin#index",:as => :main_view
  get "dashboards/new" => "dashboards#new",:as => :dashboard_view
  match "admin/disabled"=>"admin#disabled",:as=>:disabled
  match "admin/edit_account/:id"=>"admin#edit_account",:as => :edit_user_account
  match "admin/update_account" => "admin#update_account",:as => :update_account
  get "home/index"=>'home#index',:as=> :home_index
  match '/profile' => "profile#view",:as => :profile
  devise_for :users, :controllers => {:registrations => "users/registrations",
                                      :confirmations => 'users/confirmations'}
  root :to => 'home#index'
  resources :sizes
  resources :category_products
  resources :product_saved
  resources :designer_liked
 get "admin/users"=>"admin#user_details"
 match "admin/user_pro"=>"admin#user_pro"
 match "admin/select_manag"=>"admin#select_manag"
  post  "categories/create_cate"=>"categories#create_cate"
  get "categories/new"=>'categories#new'
  get "/categories"=>'categories#index'
  get "/categories/show"=>'categories#show'
  get "/categories/edit"=>'categories#edit'
  match "/categories/delete"=>'categories#destroy'
  match "/categories/update"=>'categories#update'
 
  match "/designers"=>"designers#index"
  match "/designers/create"=>"designers#create"
  match "/designers/new"=>"designers#new"
  get "/designers/show"=>"designers#show"
  get "/designers/edit"=>"designers#edit"
  match "/designers/update"=>"designers#update"
  get "/designers/delete"=>"designers#destroy"

  match "/products"=>"products#index",:as=>:product_index
  post "/product/create"=>"products#create",:as=>:product_create
  match "/product/new"=>"products#new",:as=>:product_new
  get "/product/show"=>"products#show",:as=>:product_show
  get "/product/edit"=>"products#edit",:as=>:product_edit
  match "/product/update"=>"products#update",:as=>:product_update
  get "/product/delete"=>"products#destroy",:as=>:product_delete


  get "/frontend/home"=>"frontend#home"
  get "/frontend/category_main"=>"frontend#category_main"
  get "/frontend/category_individual"=>"frontend#category_individual"
  get "/frontend/designer_main"=>"frontend#designer_main"
  get "/frontend/designer_individual"=>"frontend#designer_individual"
  get "/frontend/product_main"=>"frontend#product_main"
  match "/frontend/product_individual"=>"frontend#product_individual"
 match "/frontend/featured_subcate/:id"=>"frontend#featured_subcate" ,:as=>:frontend_featured_subcate
match "/frontend/designer_liked/:id"=>"frontend#designer_liked" ,:as=>:frontend_designer_liked
  match "/frontend/delete"=>"frontend#destroy",:as=>:frontend_delete
match "/get_prices"=>"frontend#price"
match "/data_saved"=>"frontend#res_back"

end

app/models/designer.rb
class Designer < ActiveRecord::Base
  attr_accessible :name, :description,:city,:state,:country,:image,
  :image_file_name,:image_content_type,
   	:image_file_size,:image_updated_at
  has_many :designer_likeds
  has_many :users, :through=> :designer_likeds
  has_many :products
  	has_attached_file :image,
                    :column => 'image',
                    :styles => { :small => "45x50",:medium => "90x100",:large => "180x200",:xlarge => "270x300",:xxlarge => "360x400"},
                    :default_url => "/images/designer/:style.png",
                    :url=>"/assets/designer/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/designer/:id/:style/:basename.:extension"
                    validates_attachment_content_type :image, :content_type => /\Aimage/
end

app/controllers/designers_controller.rb
class DesignersController < ApplicationController
	def index
		@designers=Designer.all
	end
	def new
		@designer=Designer.new
	end
	
	def create
		@designer=Designer.new(params[:designer])
		if @designer.save
			redirect_to designers_path
		else
			render :action=>"new"
		end
	end
	def show
		@designer=Designer.find(params[:show_did])
	end
	def edit
		@designer=Designer.find(params[:edit_did])
		
	end
	def update
		@designer=Designer.find(params[:update_did])
		if @designer.update_attributes(params[:designer])
			redirect_to designers_path
		else
			render :action=>"edit"
		end

	end
	def destroy
		
		@designer=Designer.find(params[:del_did])
		@designer.destroy
		redirect_to designers_path
	end
	
end

app/helpers/designers_helper.rb
module DesignersHelper
end

app/views/designers/edit.html.erb
<h1>Editing Designer</h1>

<%= form_for(@designer,url: designers_update_path(:update_did=>"#{@designer.id}"), html: { method: :put }) do |f| %>
	<div><%= f.label :Name%><br />
  		<%= f.text_field :name%></div>
	<div><%= f.label :Description%><br />
  		<%= f.text_area :description%></div>
	<div><%= f.label :Image %><br>
		<%=f.file_field :image %></div> 
	<div><%= f.label :City %><br>
		<%=f.text_field :city %></div>
	<div><%= f.label :State %><br>
		<%=f.text_field :state %></div>
	<div><%= f.label :Country %><br>
		<%=f.text_field :country %></div>
	<div><%= f.submit "Update"  %></div>
  	<% end %>
<%=link_to 'Show',designers_show_path(:show_did=>@designer.id)%>
<%=link_to 'Back',designers_path%>

app/views/designers/index.html.erb
<h2> Designer Details </h2>
<table>
	<tr>
		<th>Name   </th>
		<th>Description     </th>
		 <th>Image  </th> 
		  
		<th>City   </th>
		<th>State  </th>
		<th>Country</th>
		
	</tr>
	<% @designers.each do |d| %>
	<tr>
		<td><%=d.name %></td>
		<td><%=d.description  %></td>
		<td><%=image_tag(d.image.url(:small))%></td>
		
		<td><%=d.city%></td>
		<td><%=d.state%></td>
		<td><%=d.country%></td>
		<td><%= link_to "Show",designers_show_path(:show_did => d.id)%></td>
		<td><%= link_to "Edit" ,designers_edit_path(:edit_did => d.id) %></td>
		<td><%= link_to "Delete" ,designers_delete_path(:del_did => d.id)%></td>
	</tr>
	<%end%>
</table>
<br>
<%= link_to "New Designer",designers_new_path %>

app/views/designers/new.html.erb
<%= form_for(@designer,url: designers_create_path,html: {:multipart => true}) do |f| %>
	<div><%= f.label :Name %><br>
		<%= f.text_field :name %></div>
	<div><%= f.label :Description %><br>
		<%=f.text_area :description %></div>
	<div><%= f.label :Image %><br>
		<%=f.file_field :image %></div>
	<div><%= f.label :City %><br>
		<%=f.text_field :city %></div>
	<div><%= f.label :State %><br>
		<%=f.text_field :state %></div>
	<div><%= f.label :Country %><br>
		<%=f.text_field :country %></div>
	<div><%= f.submit "Submit" %></div>
		
	<%end%>

app/views/designers/show.html.erb
<p>
	<b>Name:</b>
	<%=@designer.name%>
</p>
<p>
	<b>Description:</b>
	<%=@designer.description%>
</p>
<p>
	<b>Image:</b>
	<%=image_tag(@designer.image.url(:small))%>
</p>
<p>
	<b>City:</b>
	<%=@designer.city%>
</p>
<p>
	<b>State:</b>
	<%=@designer.state%>
</p>
<p>
	<b>Country:</b>
	<%=@designer.country%>
</p>
<%=link_to 'Edit',designers_edit_path(:edit_did=>@designer.id) %>
<%=link_to 'Back' ,designers_path%>