config/routes.rb
ClothingApp::Application.routes.draw do
  get "admin/index" => "admin#index",:as => :main_view
  get "dashboards/new" => "dashboards#new",:as => :dashboard_view
  match "admin/disabled"=>"admin#disabled",:as=>:disabled
  match "admin/edit_account/:id"=>"admin#edit_account",:as => :edit_user_account
  match "admin/update_account" => "admin#update_account",:as => :update_account
  get "home/index"=>'home#index',:as=> :home_index
  match '/profile' => "profile#view",:as => :profile
  devise_for :users, :controllers => {:registrations => "users/registrations",
                                      :confirmations => 'users/confirmations'}
  root :to => 'home#index'
  resources :sizes
  resources :category_products
  resources :product_saved
  resources :designer_liked
 get "admin/users"=>"admin#user_details"
 match "admin/user_pro"=>"admin#user_pro"
 match "admin/select_manag"=>"admin#select_manag"
  post  "categories/create_cate"=>"categories#create_cate"
  get "categories/new"=>'categories#new'
  get "/categories"=>'categories#index'
  get "/categories/show"=>'categories#show'
  get "/categories/edit"=>'categories#edit'
  match "/categories/delete"=>'categories#destroy'
  match "/categories/update"=>'categories#update'
 
  match "/designers"=>"designers#index"
  match "/designers/create"=>"designers#create"
  match "/designers/new"=>"designers#new"
  get "/designers/show"=>"designers#show"
  get "/designers/edit"=>"designers#edit"
  match "/designers/update"=>"designers#update"
  get "/designers/delete"=>"designers#destroy"

  match "/products"=>"products#index",:as=>:product_index
  post "/product/create"=>"products#create",:as=>:product_create
  match "/product/new"=>"products#new",:as=>:product_new
  get "/product/show"=>"products#show",:as=>:product_show
  get "/product/edit"=>"products#edit",:as=>:product_edit
  match "/product/update"=>"products#update",:as=>:product_update
  get "/product/delete"=>"products#destroy",:as=>:product_delete


  get "/frontend/home"=>"frontend#home"
  get "/frontend/category_main"=>"frontend#category_main"
  get "/frontend/category_individual"=>"frontend#category_individual"
  get "/frontend/designer_main"=>"frontend#designer_main"
  get "/frontend/designer_individual"=>"frontend#designer_individual"
  get "/frontend/product_main"=>"frontend#product_main"
  match "/frontend/product_individual"=>"frontend#product_individual"
 match "/frontend/featured_subcate/:id"=>"frontend#featured_subcate" ,:as=>:frontend_featured_subcate
match "/frontend/designer_liked/:id"=>"frontend#designer_liked" ,:as=>:frontend_designer_liked
  match "/frontend/delete"=>"frontend#destroy",:as=>:frontend_delete
match "/get_prices"=>"frontend#price"
match "/data_saved"=>"frontend#res_back"

end

app/models/category.rb
class Category < ActiveRecord::Base
   	attr_accessible :name,:description,:parent_id,:is_featured,:image,
    :image_file_name,:image_content_type,
   	:image_file_size,:image_updated_at
  	has_many :sub_categories, :class_name => "Category",
    :foreign_key => "parent_id"
    has_many :category_products 
  has_many :products, :through => :category_products 
 	has_attached_file :image,
                    :column => 'image',
                    :styles => { :small => "45x50",:medium => "90x100",:large => "180x200",:xlarge => "270x300",:xxlarge => "360x400"},
                    :default_url => "/images/category/:style.png",
                    :url=>"/assets/category/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/category/:id/:style/:basename.:extension"
                    validates_attachment_content_type :image, :content_type => /\Aimage/

# validates :name,:presence=>true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	def index
		if params[:value]
		@categories =Category.where(:is_featured=>true)
		else
				@categories = Category.find(:all,:order=> "created_at Desc")
			end
	end
	def new
		@category = Category.new
		@parent_category=Category.where("parent_id is null").collect{|i| [i.name,i.id]}
		if params[:category]=="subcategory"
			@subcategory=true
		end
	end
	def create_cate
		@category = Category.new(params[:category])
		p @category.errors.inspect
		if @category.save
			redirect_to categories_path
		else
			render :action=>"new"
		end
	end
	def show
		@c1=Category.find(params[:category_id])
	end
	def edit
		@c1=Category.find(params[:edit_cid])
	end
	def update
		
		@category=Category.find(params[:id])
		if @category.update_attributes(params[:category])
			redirect_to categories_path
		else
			render :action=>"edit"
		end
	end
	def destroy
		@category=Category.find(params[:del_cid])
		@category.destroy
		redirect_to categories_path
	end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<h1>Editing Category</h1>
<%= form_for(@c1,url: categories_update_path(:id=>"#{@c1.id}"), html: { method: :put }) do |f| %>

<div><%= f.label :Name%><br />
  	<%= f.text_field :name%></div>
<div><%= f.label :Description%><br />
  	<%= f.text_area :description%></div>
 <div><%= f.label :is_featured%><br />
  	<%= f.check_box :is_featured%></div>
  	
 <div><%= f.label :Image%><br />
  	<%= f.file_field :image%></div>
 <div><%= f.submit "Update"  %></div>
  	<% end %>
<%=link_to 'Show',categories_show_path(:category_id=>@c1.id)%>
<%=link_to 'Back',categories_path%>

app/views/categories/index.html.erb
<h1>Listing categories</h1>
 
<table>
  <tr>
    <th>ID</th>
    <th>Name</th>
    <th>Description</th>
    <th>Image</th>
    <th>Is_featured</th>
    <th>Parent_id</th>
    <th></th>
    <th></th> 
    <th></th> 
  </tr>
 
<% @categories.each do |c| %>
  <tr>
  <td><%= c.id %></td>
    <td><%= c.name %></td>
    <td><%= c.description %></td>
    <td><%=image_tag(c.image.url(:small))%></td> 
    <td><%= c.is_featured %></td>
    <td><% c.sub_categories.each do|s| %>
      <%=s.name%><br>
      <%end%></td>
    <td><%= link_to 'Show', categories_show_path(:category_id=>c.id) %></td>
    <td><%= link_to 'Edit', categories_edit_path(:edit_cid=>c.id) %></td>
    <td><%= link_to 'Destroy', categories_delete_path(:del_cid=>c.id)
                                      %></td>
  </tr>
<% end %>
</table>
 
<br />
 
<%= link_to 'New Category', categories_new_path %>
<%= link_to 'New SubCategory', categories_new_path(:category=>"subcategory") %>

app/views/categories/new.html.erb
<%= form_for(@category,url: categories_create_cate_path, html: { :id=>"cate_form" , method: :post ,:multipart => true}) do |f| %>

<div><%= f.label :Name%><br />
  	<%= f.text_field :name , :id=>"cate_name"%></div>
<div><%= f.label :Description%><br />
  	<%= f.text_area :description%></div>
 <div><%= f.label :is_featured%><br />
  	<%= f.check_box :is_featured%></div>
  	
  	<%if @subcategory%>
<div><%= f.label :Parent_id%><br />
 	<%=f.select :parent_id, options_for_select(@parent_category)%>
</div>
<%end%>
 <div><%= f.label :Image%><br />
  	<%= f.file_field :image%></div>
 <div><%= f.submit "Submit" %></div>
  	<% end %>

app/views/categories/show.html.erb
<p>
	<b>Name:</b>
	<%=@c1.name%>
</p>
<p>
	<b>Description:</b>
	<%=@c1.description%>
</p>
<p>
	<b>Image:</b>
	<%=image_tag(@c1.image.url(:small))%>
</p>
<%=link_to 'Edit',categories_edit_path(:edit_cid=>@c1.id) %>
<%=link_to 'Back' ,categories_path%>