config/routes.rb
ClothingApp::Application.routes.draw do
  get "admin/index" => "admin#index",:as => :main_view
  get "dashboards/new" => "dashboards#new",:as => :dashboard_view
  match "admin/disabled"=>"admin#disabled",:as=>:disabled
  match "admin/edit_account/:id"=>"admin#edit_account",:as => :edit_user_account
  match "admin/update_account" => "admin#update_account",:as => :update_account
  get "home/index"=>'home#index',:as=> :home_index
  match '/profile' => "profile#view",:as => :profile
  devise_for :users, :controllers => {:registrations => "users/registrations",
                                      :confirmations => 'users/confirmations'}
  root :to => 'home#index'
  resources :sizes
  resources :category_products
  resources :product_saved
  resources :designer_liked
 get "admin/users"=>"admin#user_details"
 match "admin/user_pro"=>"admin#user_pro"
 match "admin/select_manag"=>"admin#select_manag"
  post  "categories/create_cate"=>"categories#create_cate"
  get "categories/new"=>'categories#new'
  get "/categories"=>'categories#index'
  get "/categories/show"=>'categories#show'
  get "/categories/edit"=>'categories#edit'
  match "/categories/delete"=>'categories#destroy'
  match "/categories/update"=>'categories#update'
 
  match "/designers"=>"designers#index"
  match "/designers/create"=>"designers#create"
  match "/designers/new"=>"designers#new"
  get "/designers/show"=>"designers#show"
  get "/designers/edit"=>"designers#edit"
  match "/designers/update"=>"designers#update"
  get "/designers/delete"=>"designers#destroy"

  match "/products"=>"products#index",:as=>:product_index
  post "/product/create"=>"products#create",:as=>:product_create
  match "/product/new"=>"products#new",:as=>:product_new
  get "/product/show"=>"products#show",:as=>:product_show
  get "/product/edit"=>"products#edit",:as=>:product_edit
  match "/product/update"=>"products#update",:as=>:product_update
  get "/product/delete"=>"products#destroy",:as=>:product_delete


  get "/frontend/home"=>"frontend#home"
  get "/frontend/category_main"=>"frontend#category_main"
  get "/frontend/category_individual"=>"frontend#category_individual"
  get "/frontend/designer_main"=>"frontend#designer_main"
  get "/frontend/designer_individual"=>"frontend#designer_individual"
  get "/frontend/product_main"=>"frontend#product_main"
  match "/frontend/product_individual"=>"frontend#product_individual"
 match "/frontend/featured_subcate/:id"=>"frontend#featured_subcate" ,:as=>:frontend_featured_subcate
match "/frontend/designer_liked/:id"=>"frontend#designer_liked" ,:as=>:frontend_designer_liked
  match "/frontend/delete"=>"frontend#destroy",:as=>:frontend_delete
match "/get_prices"=>"frontend#price"
match "/data_saved"=>"frontend#res_back"

end

app/models/product.rb
class Product < ActiveRecord::Base
 attr_accessible :name, :description,:sku,:image,:price,:is_featured, :designer_id,
 :image_file_name,:image_content_type,
   	:image_file_size,:image_updated_at
    has_many :category_products
 has_many :categories, :through => :category_products 
 belongs_to :designer
 has_many :product_saveds
 has_many :sizes
 has_attached_file :image,
                    :column => 'image',
                    :styles => { :small => "45x50",:medium => "90x100",:large => "180x200",:xlarge => "270x300",:xxlarge => "360x400"},
                    :default_url => "/images/product/:style.png",
                    :url=>"/assets/product/:id/:style/:basename.:extension",
                    :path => ":rails_root/public/assets/product/:id/:style/:basename.:extension"
                    validates_attachment_content_type :image, :content_type => /\Aimage/
before_create :generate_desig
 def generate_desig
 	if self.sku.nil? and self.new_record? 
 		self.sku=random_string(16)
 	end
 end
def random_string(length)
	chars = 'abcdefghjkmnpqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ123456789'
	random = ''
	length.times { random << chars[rand(chars.size)] }
 return random

end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,:name,:city,:state,:country,:is_disabled,:role
  has_many :designer_likeds
  has_many :designers, :through=> :designer_likeds
  has_many :products
  has_many :product_saveds
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
	def index
		if params[:value]
			@products=Product.where(:is_featured=>true)
		else
		@products=Product.all
	end
	end
	def new
		@product=Product.new
		@designer_ids=Designer.all.collect{|i|[i.name,i.id]}
	end
	
	def create
		@product=Product.new(params[:product])
		if @product.save
			redirect_to product_index_path
		else
			render :action=>"new"
		end
	end
	def show
		@product = Product.find(params[:show_pid])
	end
	def edit
		@product=Product.find(params[:edit_pid])

	end
	def update
		@product=Product.find(params[:update_pid])
		if @product.update_attributes(params[:product])
			redirect_to product_index_path
		else 
			render :action=>"edit"
		end
	end
	def destroy
		@product=Product.find(params[:del_pid])
		@product.destroy
		redirect_to product_index_path
	end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>Editing Products</h1>

<%= form_for(@product,url: product_update_path(:update_pid=>"#{@product.id}"), html: { method: :put }) do |f| %>
	<div><%= f.label :Name%><br />
  		<%= f.text_field :name%></div>
	<div><%= f.label :Description%><br />
  		<%= f.text_area :description%></div>
	<div><%= f.label :Image %><br>
		<%=f.file_field :image %></div> 
	<div><%= f.label :Is_featured%><br />
  	<%= f.check_box :is_featured%></div>
<div><%#= f.label :Designer_id%><br />
 	<%#=f.select :designer_id, options_for_select(@designer_ids)%></div>
 <div><%= f.label :Price%><br />
  	<%= f.text_field :price%></div>
	<div><%= f.submit "Update"  %></div>
  	<% end %>
<%=link_to 'Show',product_show_path(:show_pid=>@product.id)%>
<%=link_to 'Back',product_index_path%>

app/views/products/index.html.erb
<h2> Product Details </h2>
<table>
	<tr>
		<th>   </th>
		<th>Name   </th>
		<th>Description </th>
		<th>Image  </th> 
		<th>SKU   </th>
		<th>Designer_id </th>
		<th>Price</th>
		<th>Is_featured</th>
		
	</tr>
	<% @products.each do |p| %>
	<tr>
		<td><%=p.id %></td>
		<td><%=p.name %></td>
		<td><%=p.description  %></td>
		<td><%=image_tag(p.image.url(:small))%></td> 
		<td><%=p.sku%></td>
		<td><%=p.designer_id%></td>
		<td><%=p.price%></td>
		<td><%=p.is_featured%></td>
		<td><%= link_to "Show", product_show_path(:show_pid => p.id) %></td>
		<td><%= link_to "Edit" ,product_edit_path(:edit_pid => p.id)%></td>
		<td><%= link_to "Delete" ,product_delete_path(:del_pid => p.id)%></td>
	</tr>
	<%end%>
</table>
<br>
<%= link_to "New Product", product_new_path %>

app/views/products/new.html.erb
<h1> New Products </h1>
<%= form_for(@product,url: product_create_path,html: { :multipart => true}) do |f| %>

<div><%= f.label :Name%><br />
  	<%= f.text_field :name%></div>
<div><%= f.label :Description%><br />
  	<%= f.text_area :description%></div>
<div><%= f.label :Image%><br />
  	<%= f.file_field :image%></div>
<div><%= f.label :Is_featured%><br />
  	<%= f.check_box :is_featured%></div>
<div><%= f.label :Designer_id%><br />
 	<%=f.select :designer_id, options_for_select(@designer_ids)%></div>
 <div><%= f.label :Price%><br />
  	<%= f.text_field :price%></div>
<div><%= f.submit "Submit" %></div>
  	<% end %>

app/views/products/show.html.erb
<p>
	<b>Name:</b>
	<%=@product.name%>
</p>
<p>
	<b>Description:</b>
	<%=@product.description%>
</p>
<p>
	<b>Image:</b>
	<%=image_tag(@product.image.url(:small))%>
</p>
<p>
	<b>SKU:</b>
	<%=@product.sku%>
</p>
<p>
	<b>Designer_id:</b>
	<%=@product.designer_id%>
</p>
<p>
	<b>Price:</b>
	<%=@product.price%>
</p>
<p>
	<b>Is_featured:</b>
	<%=@product.is_featured%>
</p>
<%=link_to 'Edit',product_edit_path(:edit_pid=>@product.id) %>
<%=link_to 'Back' ,product_index_path%>